### ISSUE TITLE
Explore possibility of reconnecting to Omnia after a disconnect.

### ISSUE THREAD

**Issue by zflerner** [naubiomech/HLO#2]

**Comment by go226** [comment]
Cosmed customer support says that it is possible to reconnect through Omnia after a disconnect but the data will be lost and a new test will have to be started. The walks we do are within the operating range of the standard bluetooth device on the K5 (100 ft) but line-of-sight is important for maintaining the connection. A more powerful bluetooth adapter is available for $4000 that works up to 1000 meters and doesn't need line-of-sight. I requested a quote just to have it but since this issue is so rare we can take other steps to prevent it such as moving the computers to the center of the room.
